- name: Deploy to VM
  uses: appleboy/ssh-action@v1.0.3
  with:
    host: 62.122.210.118
    username: david
    key: ${{ secrets.SSH_PRIVATE_KEY }}
    port: 22
    script: |
      cd /home/***/flask
      ./deploy.sh
